num1 = int(input("enter a number"))
num2 = int(input("enter a number"))
num3 = int(input("enter a number"))
num4 = int(input("enter a number"))
num5 = int(input("enter a number"))
num6 = int(input("enter a number"))
num7 = int(input("enter a number"))
num8 = int(input("enter a number"))
s = {num1,num2,num3,num4,num5,num6,num7,num8}
print(s)